# Generated by Django 4.2.7 on 2026-03-23 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Kelishilgan narx')),
                ('status', models.CharField(choices=[('kutilyapti', 'Kutilyapti'), ('kelishilgan', 'Kelishilgan'), ('sotib olingan', 'Sotib olingan'), ('bekor qilingan', 'Bekor qilingan')], default='kutilyapti', max_length=20, verbose_name='Status')),
                ('meeting_location', models.CharField(blank=True, max_length=300, verbose_name='Uchrashuv joyi')),
                ('meeting_time', models.DateTimeField(blank=True, null=True, verbose_name='Uchrashuv vaqti')),
                ('notes', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
