# Generated by Django 4.2.7 on 2026-03-23 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Username')),
                ('first_name', models.CharField(max_length=150, verbose_name='Ism')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Familiya')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Telefon raqami')),
                ('role', models.CharField(choices=[('customer', 'Xaridor'), ('seller', 'Sotuvchi')], default='customer', max_length=10, verbose_name='Rol')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Profil rasmi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Admin')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Ro'yxatdan o'tgan sana")),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi kirish')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=200, unique=True, verbose_name="Do'kon nomi")),
                ('shop_description', models.TextField(blank=True, verbose_name="Do'kon tavsifi")),
                ('shop_logo', models.ImageField(blank=True, null=True, upload_to='shop_logos/', verbose_name="Do'kon logosi")),
                ('region', models.CharField(max_length=100, verbose_name='Viloyat')),
                ('district', models.CharField(max_length=100, verbose_name='Tuman')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Manzil')),
                ('rating', models.FloatField(default=0.0, verbose_name='Reyting')),
                ('total_sales', models.PositiveIntegerField(default=0, verbose_name='Sotuvlar soni')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Sotuvchi profili',
                'verbose_name_plural': 'Sotuvchi profillari',
                'ordering': ['-rating'],
            },
        ),
    ]
